parameters:
     open_middleware.api.gateway: https://openmiddleware.pl/orange/oracle/
     open_middleware.api.user: user
     open_middleware.api.password: pass

services:
    http_client:
        class: Guzzle\Http\Client
        arguments: [%open_middleware.api.gateway%]

    open_middleware.api:
        class: OpenMiddleware\Bundle\Api\Api
        arguments: [@http_client, %open_middleware.api.user%, %open_middleware.api.password%]

    open_middleware.api.sms:
        class: OpenMiddleware\Bundle\Api\SmsApi
        parent: open_middleware.api

    open_middleware.api.ussd:
        class: OpenMiddleware\Bundle\Api\UssdApi
        parent: open_middleware.api